sudo: false
language: generic

addons:
  apt:
    update: true
    packages:
    - libgmp-dev
  homebrew:
    update: true
    packages:
    - z3
    - upx
    - gnu-tar

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal/
  - $HOME/.local/bin
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/brittany/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/HaRe/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/ghc-mod/core/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/haskell-lsp/haskell-lsp-types/.stack-work
  - $TRAVIS_BUILD_DIR/submodules/cabal-helper/.stack-work
  - $TRAVIS_BUILD_DIR/hie-plugin-api/.stack-work
  timeout: 2000
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/.stack-work/logs/

stages:
  - setup
  - lens
  - dependencies
  - build
  - test

jobs:
   include:

   # Ubuntu
   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.4.2"
     script: &setup
       - export DIR=$HOME/.local/bin
       - if [ ! -d "$DIR" ]; then mkdir -p $HOME/.local/bin; fi
       - export PATH=$HOME/.local/bin:$PATH
       - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
       - stack --version
       - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.4.3"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.4.4"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.6.1"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.6.2"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.6.3"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.6.4"
     script: *setup

   - stage: setup
     os: linux
     dist: bionic
     env: GHC_VER="8.6.5"
     script: *setup

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.4.2"
     script: &lens
       - export PATH=$HOME/.local/bin:$PATH
       - ls .stack-work/install/*/*/*/bin/hie || true
       # Build a big package to offload the next stage from doing too much work
       - stack --stack-yaml=stack-$GHC_VER.yaml build lens aeson alex conduit

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.4.3"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.4.4"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.6.1"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.6.2"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.6.3"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.6.4"
     script: *lens

   - stage: lens
     os: linux
     dist: bionic
     env: GHC_VER="8.6.5"
     script: *lens

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.4.2"
     script: &dependencies
       - export PATH=$HOME/.local/bin:$PATH
       - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml build --only-dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.4.3"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.4.4"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.6.1"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.6.2"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.6.3"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.6.4"
     script: *dependencies

   - stage: dependencies
     os: linux
     dist: bionic
     env: GHC_VER="8.6.5"
     script: *dependencies

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.4.2"
     script: &build
       - export PATH=$HOME/.local/bin:$PATH
       - stack --no-terminal --stack-yaml=stack-$GHC_VER.yaml build
       - stack --no-terminal --stack-yaml=stack-$GHC_VER.yaml install

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.4.3"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.4.4"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.6.1"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.6.2"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.6.3"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.6.4"
     script: *build

   - stage: build
     os: linux
     dist: bionic
     env: GHC_VER="8.6.5"
     script: *build

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.4.2"
     script: &test
       - export PATH=$HOME/.local/bin:$PATH
       - stack --no-terminal --stack-yaml=stack-$GHC_VER.yaml test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.4.3"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.4.4"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.6.1"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.6.2"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.6.3"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.6.4"
     script: *test

   - stage: test
     os: linux
     dist: bionic
     env: GHC_VER="8.6.5"
     script: *test

   # OS X
   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.2"
     script: &setuposx
       - export DIR=$HOME/.local/bin
       - if [ ! -d "$DIR" ]; then mkdir -p $HOME/.local/bin; fi
       - export PATH=$HOME/.local/bin:$PATH
       - travis_retry curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
       - stack --version
       - travis_retry stack --no-terminal --install-ghc --stack-yaml=stack-$GHC_VER.yaml setup

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.3"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.4"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.1"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.2"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.3"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.4"
     script: *setuposx

   - stage: setup
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.5"
     script: *setuposx

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.2"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.3"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.4"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.1"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.2"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.3"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.4"
     script: *lens

   - stage: lens
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.5"
     script: *lens

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.2"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.3"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.4"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.1"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.2"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.3"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.4"
     script: *dependencies

   - stage: dependencies
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.5"
     script: *dependencies

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.2"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.3"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.4"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.1"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.2"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.3"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.4"
     script: *build

   - stage: build
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.5"
     script: *build

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.2"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.3"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.4.4"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.1"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.2"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.3"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.4"
     script: *test

   - stage: test
     os: osx
     osx_image: xcode11.2
     env: GHC_VER="8.6.5"
     script: *test
