version: 1.0.{build}
environment:
  matrix:
  - GHCVER: 8.4.3
  - GHCVER: 8.4.2
  - GHCVER: 8.2.2
  - GHCVER: 8.2.1
install:
- cmd: >-
    git submodule update --init --recursive

    choco install -y haskell-stack

    refreshenv
cache:
- '%LOCALAPPDATA%\Programs\stack\'
- c:\sr
build_script:
- cmd: stack --stack-yaml=stack-%GHCVER%.yaml install
test: off
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: ae8337b11de3463a15224f6ff05f2a6081ff3098
  artifacts:
    - .stack-work\install\**\bin\hie.exe
    - .stack-work\install\**\bin\hie-wrapper.exe
  on:
    branch: master
    appveyor_repo_tag: true
