resolver: nightly-2019-07-31 # GHC 8.6.5
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core
- ./submodules/ghc-mod/ghc-project-types

- ansi-terminal-0.8.2
- ansi-wl-pprint-0.6.8.2
- brittany-0.12.0.0
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- floskell-0.10.1
- ghc-lib-parser-8.8.0.20190723
- haddock-api-2.22.0
- haskell-lsp-0.15.0.0
- haskell-lsp-types-0.15.0.0
- hlint-2.2.2
- hsimport-0.10.0
- lsp-test-0.6.0.0
- monad-dijkstra-0.1.1.2@rev:1
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32
- network-3.0.1.1
- network-bsd-2.8.1.0
- hslogger-1.3.0.0

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
