resolver: nightly-2017-06-16
packages:
- .
- hie-apply-refact
- hie-base
- hie-build-plugin
- hie-eg-plugin-async
- hie-example-plugin2
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-hoogle
- hie-plugin-api
- hie-brittany
- hie-haddock
- location:
    git: https://github.com/alanz/haskell-lsp.git
    commit: fe2289c6cd16620bb93aacd263aadb59a01f2ca7
  extra-dep: true

- location:
    git: https://github.com/alanz/ghc-dump-tree.git
    commit: 9dbca928ad5507b144f46bb95123a08d24f24808
  extra-dep: true
- location:
    git: https://github.com/alanz/HaRe.git
    commit: f3b4fd1b65007184df9bb7743d29a4347057a422
  extra-dep: true
- location:
    git: https://github.com/wz1000/ghc-mod.git
    commit: 55ac67bdb4eb3816df5569f63e96fa2087dab205
  extra-dep: true
  subdirs:
    - .
    - ghc-mod-core

extra-deps:
- apply-refact-0.3.0.1
- butcher-1.1.0.1
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- deque-0.2
- monad-memo-0.4.1
- hoogle-5.0.13
- brittany-0.8.0.2
- yi-rope-0.10
flags:
  haskell-ide-engine:
    pedantic: true
  hie-apply-refact:
    pedantic: true
  hie-base:
    pedantic: true
  hie-eg-plugin-async:
    pedantic: true
  hie-example-plugin2:
    pedantic: true
  hie-ghc-mod:
    pedantic: true
  hie-ghc-tree:
    pedantic: true
  hie-hare:
    pedantic: true
  hie-hoogle:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  hie-brittany:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
