resolver: nightly-2018-06-01
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/cabal-helper
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/yi-rope
  extra-dep: true

- location:
    ./submodules/haskell-lsp
  extra-dep: true
  subdirs:
    - .
    - haskell-lsp-types

extra-deps:
- apply-refact-0.5.0.0
- brittany-0.11.0.0
- constrained-dynamic-0.1.0.0
- haddock-api-2.20.0
- haddock-library-1.6.0
# - haskell-lsp-0.2.2.0
# - haskell-lsp-types-0.2.2.0
- syz-0.2.0.0
- temporary-1.2.1.1

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
