jobs:
- job: Windows_installhs_Cabal
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  variables:
    YAML_FILE: install/shake.yaml
    PROJECT_FILE: install/shake.project
    STACK_ROOT: "C:\\sr"
  # TODO: Replace stack with chocolatey for installing ghc and cabal
  steps:
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack install Cabal-3.0.0.0 cabal-install-3.0.0.0 --stack-yaml $(YAML_FILE)
    displayName: Install `cabal-install`
  - bash: |
      source .azure/windows.bashrc
      cabal v2-update
    displayName: update cabal
  - bash: |
      source .azure/windows.bashrc
      GHC_PATH=$(stack path --stack-yaml $YAML_FILE --compiler-exe)
      cabal v2-run install.hs -w $GHC_PATH --project-file $(PROJECT_FILE) help
    displayName: Run help of `install.hs`
  # - bash: |
  #    source .azure/windows.bashrc
  #    GHC_PATH=$(stack path --stack-yaml $YAML_FILE --compiler-exe)
  #    GHC_DIR=$(dirname $GHC_PATH)
  #    export PATH=$(cygpath $GHC_DIR):$PATH
  #    cabal v2-run install.hs -w $GHC_PATH --project-file $(PROJECT_FILE) build-latest
  #  displayName: Run build-latest target of `install.hs`
