jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
  variables:
    STACK_ROOT: "C:\\sr"

  steps:
  - task: Cache@2
    inputs:
      key: '"stack-root" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache stack-root"
  - bash: |
      mkdir -p $STACK_ROOT
      tar -vxzf .azure-cache/stack-root.tar.gz -C /
      mkdir -p .stack-work
      tar -vxzf .azure-cache/stack-work.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/windows.bashrc
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required locally for tests
      mkdir .azure-deploy
      stack install --stack-yaml $(YAML_FILE) --local-bin-path .azure-deploy 
      cd .azure-deploy
      if [ $YAML_FILE != "stack.yaml" ]; then
        GHC_MINOR_VERSION=${YAML_FILE:6:5}
        GHC_MAJOR_VERSION=${YAML_FILE:6:3}
        cp hie.exe hie-$GHC_MINOR_VERSION.exe
        cp hie.exe hie-$GHC_MAJOR_VERSION.exe
      else
        GHC_MINOR_VERSION=nightly
      fi
      stack unpack hlint --stack-yaml ../$(YAML_FILE) --to "$(Agent.TempDirectory)"
      mkdir -p data
      cp "$(Agent.TempDirectory)"/hlint*/data/hlint.yaml data
      ARTIFACT_NAME=hie-$(hie --numeric-version)-ghc-$GHC_MINOR_VERSION-windows-x86_64
      7z a "$(Build.ArtifactStagingDirectory)/$ARTIFACT_NAME.zip" *
    displayName: Install `hie` 
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
    displayName: Build Test-dependencies
  - bash: |
      # TODO: try to install automatically (`choco install z3` fails and pacman is not installed)
      mkdir -p /usr/local
      curl -L https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip -o /usr/local/z3.zip
      unzip -o /usr/local/z3.zip -d /usr/local/
    displayName: "Install Runtime Test-Dependencies: z3"
  - bash: |
      source .azure/windows.bashrc
      stack install --resolver=lts-13.20 liquid-fixpoint-0.8.0.2 liquidhaskell-0.8.6.2
    displayName: "Install Runtime Test-Dependencies: liquidhaskell"
  - bash: |
      source .azure/windows.bashrc
      stack build hoogle --stack-yaml=$(YAML_FILE)
      stack exec hoogle generate --stack-yaml=$(YAML_FILE)
    displayName: "Install Runtime Test-Dependencies: hoogle database"
  - bash: |
      source .azure/windows.bashrc
      choco install cabal
      /C/ProgramData/chocolatey/bin/RefreshEnv.cmd
    displayName: "Install Runtime Test-Dependencies: cabal"
  - bash: |
      source .azure/windows.bashrc
      # TODO: Enable CabalHelper unit tests, see https://github.com/DanielG/cabal-helper/issues/91
      if [ $YAML_FILE = "stack-8.6.4.yaml" ]; then
        TEST_ARGS=--test-arguments="--skip=CabalHelper"
      fi
      # TODO: Enable rest of test suites
      stack test --stack-yaml $(YAML_FILE) :unit-test :plugin-dispatcher-test $TEST_ARGS # :dispatcher-test  :wrapper-test
      # TODO: Enable failing functional test
      if [ $YAML_FILE != "stack-8.6.4.yaml" ]; then
          stack test --stack-yaml $(YAML_FILE) :func-test
      else
          stack test --stack-yaml $(YAML_FILE) :func-test --ta="--skip \"/Hover/hover/works\""
      fi
    displayName: Run Test
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: hie-$(Agent.OS)-$(YAML_FILE)
    condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')
  - bash: |
      mkdir -p .azure-cache
      tar -vczf .azure-cache/stack-root.tar.gz $(cygpath $STACK_ROOT)
      tar -vczf .azure-cache/stack-work.tar.gz .stack-work
    displayName: "Pack cache"
  