jobs:
- job: Windows_installhs_Cabal
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  variables:
    GHC_VERSION: "8.6.5"
    CABAL_VERSION: "3.0.0.0"
    CABAL_DIR: "" # To use the default one (cabal-hie-install latest fails with a custom one)
    CABAL_STORE_DIR: "D:\\sd"
    PROJECT_FILE: "./install/shake.project"
  steps:
  - task: Cache@2
    inputs:
      key: '"cabal-installhs" | "$(Agent.OS)" | "$(CABAL_VERSION)" | "$(GHC_VERSION)" | $(Build.SourcesDirectory)/cabal.project | $(Build.SourcesDirectory)/haskell-ide-engine.cabal | $(Build.SourcesDirectory)/hie-plugin-api/hie-plugin-api.cabal'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Download cache"
  - bash: |
      source .azure/windows-cabal.bashrc
      mkdir -p $CABAL_ROOT
      tar -vxzf .azure-cache/cabal-root.tar.gz -C /d
      mkdir -p $CABAL_STORE_DIR
      tar -vxzf .azure-cache/cabal-store.tar.gz -C /d
      mkdir -p ./dist-newstyle
      tar -vxzf .azure-cache/cabal-dist.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      choco install -y --ignore-dependencies ghc --version=$GHC_VERSION
    displayName: Install ghc
  - bash: |
      source .azure/windows-cabal.bashrc
      choco install -y cabal --version=$CABAL_VERSION
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
    displayName: Install cabal
  - bash: |
      source .azure/windows-cabal.bashrc
      cabal v2-update
      echo "store-dir: $CABAL_STORE_DIR" >> $CABAL_ROOT/config
    displayName: Update cabal
  - bash: |
      source .azure/windows-cabal.bashrc
      cabal v2-run ./install.hs --project-file $PROJECT_FILE help
    displayName: Run help of `install.hs`
  - bash: |
      source .azure/windows-cabal.bashrc
      cabal v2-run ./install.hs --project-file $PROJECT_FILE latest
    displayName: Run build-latest target of `install.hs`
  - bash: |
      source .azure/windows-cabal.bashrc
      mkdir -p .azure-cache
      tar -vczf .azure-cache/cabal-root.tar.gz $CABAL_ROOT
      tar -vczf .azure-cache/cabal-store.tar.gz $(cygpath $CABAL_STORE_DIR)
      tar -vczf .azure-cache/cabal-dist.tar.gz dist-newstyle
    displayName: "Pack cache"

